In [1]:
#Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

excel_path_2017 = "Resources/state_M2017_dl.xlsx"
excel_path_2016 = "Resources/state_M2016_dl.xlsx"
excel_path_2015 = "Resources/state_M2015_dl.xlsx"
excel_path_2014 = "Resources/state_M2014_dl.xlsx"
excel_path_2013 = "Resources/state_M2013_dl.xlsx"

In [2]:
#read the excel file
state17_df = pd.read_excel(excel_path_2017, index_col=None)
state16_df = pd.read_excel(excel_path_2016, index_col=None)
state15_df = pd.read_excel(excel_path_2015, index_col=None)
state14_df = pd.read_excel(excel_path_2014, index_col=None)
state13_df = pd.read_excel(excel_path_2013, index_col=None)
state13_df.head()

,AREA,ST,STATE,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_Q,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,1,AL,Alabama,00-0000,All Occupations,total,1844080,0.4,1000,1,...,14.61,23.64,35.4,17200,20010,30390,49180,73620,NaN,NaN
1,1,AL,Alabama,11-0000,Management Occupations,major,66820,1.1,36.233,0.73,...,44.53,61.52,86.05,51190,68650,92610,127970,178980,NaN,NaN
2,1,AL,Alabama,11-1011,Chief Executives,detailed,1300,11.1,0.705,0.38,...,83.98,#,#,87940,117790,174690,#,#,NaN,NaN
3,1,AL,Alabama,11-1021,General and Operations Managers,detailed,26490,1.7,14.364,0.96,...,49.06,71.18,#,58470,74340,102050,148050,#,NaN,NaN
4,1,AL,Alabama,11-1031,Legislators,detailed,1400,9.8,0.76,1.81,...,*,*,*,16110,17010,18510,21340,36190,True,NaN

In [3]:
comp_math = ['15-0000','15-1121','15-1122','15-1131',
            '15-1132','15-1133','15-1134','15-1141',
            '15-1142','15-1143','15-1151','15-1152',
            '15-1199','15-2031','15-2041']

In [4]:
com_math_17_df = state17_df.loc[state17_df['OCC_CODE'].isin(comp_math)]
com_math_17_df

,AREA,ST,STATE,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,m,JOBS_1000,LOC_Q,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
63,1,AL,Alabama,15-0000,Computer and Mathematical Occupations,major,39760,2.3,20.68,0.69,...,37.3,49.05,61.78,42150,56630,77590,102020,128500,NaN,NaN
64,1,AL,Alabama,15-1121,Computer Systems Analysts,detailed,4010,9.4,2.084,0.51,...,37.89,46.97,56.72,53510,64190,78800,97710,117970,NaN,NaN
65,1,AL,Alabama,15-1122,Information Security Analysts,detailed,1100,7.8,0.573,0.78,...,42.15,53.51,61.89,54360,66790,87660,111290,128720,NaN,NaN
66,1,AL,Alabama,15-1131,Computer Programmers,detailed,7420,4.6,3.858,2.22,...,40.49,51.08,65.95,47700,62640,84230,106240,137180,NaN,NaN
67,1,AL,Alabama,15-1132,"Software Developers, Applications",detailed,5540,5.5,2.883,0.48,...,43,55.35,66.43,52150,67410,89440,115120,138180,NaN,NaN
68,1,AL,Alabama,15-1133,"Software Developers, Systems Software",detailed,3720,8.7,1.933,0.7,...,47.04,60.66,74.9,65460,77410,97840,126180,155800,NaN,NaN
69,1,AL,Alabama,15-1134,Web Developers,detailed,600,10.8,0.313,0.35,...,26.36,34.82,45.73,32750,43500,54840,72430,95130,NaN,NaN
70,1,AL,Alabama,15-1141,Database Administrators,detailed,1910,9,0.991,1.24,...,39.08,48.48,58.82,49070,61730,81290,100830,122340,NaN,NaN
71,1,AL,Alabama,15-1142,Network and Computer Systems Administrators,detailed,4230,3.3,2.201,0.84,...,33.95,43.47,53.22,44990,55980,70610,90430,110700,NaN,NaN
72,1,AL,Alabama,15-1143,Computer Network Architects,detailed,830,7.7,0.429,0.39,...,48.26,59.21,69.98,65500,79490,100380,123160,145560,NaN,NaN
73,1,AL,Alabama,15-1151,Computer User Support Specialists,detailed,5930,6,3.084,0.72,...,22.1,28.14,35.47,29570,36250,45980,58540,73770,NaN,NaN
74,1,AL,Alabama,15-1152,Computer Network Support Specialists,detailed,1000,7.7,0.523,0.4,...,29.24,36.47,44.38,37400,46960,60810,75860,92300,NaN,NaN
75,1,AL,Alabama,15-1199,"Computer Occupations, All Other",detailed,1810,3.9,0.94,0.42,...,41.64,49.51,56.88,58120,72160,86610,102980,118310,NaN,NaN
77,1,AL,Alabama,15-2031,Operations Research Analysts,detailed,670,9.5,0.35,0.47,...,44.85,57.24,69.89,48080,63570,93300,119070,145370,NaN,NaN
78,1,AL,Alabama,15-2041,Statisticians,detailed,180,4,0.093,0.36,...,29.63,36.85,45.1,40700,48290,61630,76650,93820,NaN,NaN
784,2,AK,Alaska,15-0000,Computer and Mathematical Occupations,major,5450,6.8,17.124,0.57,...,36.92,47.13,59.75,42890,56840,76800,98040,124290,NaN,NaN
785,2,AK,Alaska,15-1121,Computer Systems Analysts,detailed,860,16.2,2.695,0.66,...,35.41,45.16,51.72,35280,47740,73660,93930,107580,NaN,NaN
786,2,AK,Alaska,15-1122,Information Security Analysts,detailed,70,35.8,0.23,0.31,...,45.34,52.12,72.43,49960,80770,94310,108400,150660,NaN,NaN
787,2,AK,Alaska,15-1131,Computer Programmers,detailed,600,8.2,1.877,1.08,...,41.15,49.15,61.93,53120,67600,85590,102230,128820,NaN,NaN
788,2,AK,Alaska,15-1132,"Software Developers, Applications",detailed,340,23.5,1.056,0.18,...,*,*,*,*,*,*,*,*,NaN,NaN
789,2,AK,Alaska,15-1133,"Software Developers, Systems Software",detailed,130,41.1,0.395,0.14,...,*,*,*,*,*,*,*,*,NaN,NaN
790,2,AK,Alaska,15-1134,Web Developers,detailed,190,18.7,0.603,0.68,...,25.9,36.09,44.84,35390,42080,53860,75070,93270,NaN,NaN
791,2,AK,Alaska,15-1141,Database Administrators,detailed,200,9.7,0.635,0.8,...,37.12,48.22,59.75,44310,58200,77210,100300,124290,NaN,NaN
792,2,AK,Alaska,15-1142,Network and Computer Systems Administrators,detailed,1020,15.8,3.213,1.22,...,38.45,47.49,60.13,54270,63780,79970,98790,125080,NaN,NaN
793,2,AK,Alaska,15-1143,Computer Network Architects,detailed,90,30.8,0.281,0.25,...,48.5,58.83,75.94,37500,84560,100880,122360,157950,NaN,NaN
794,2,AK,Alaska,15-1151,Computer User Support Specialists,detailed,830,6.7,2.623,0.61,...,27.51,33.89,42.11,39010,46550,57220,70480,87580,NaN,NaN
795,2,AK,Alaska,15-1152,Computer Network Support Specialists,detailed,320,10.8,1.012,0.77,...,26.62,33.05,43.8,40180,45940,55370,68740,91100,NaN,NaN
796,2,AK,Alaska,15-1199,"Computer Occupations, All Other",detailed,540,6.8,1.703,0.77,...,44.1,51,57.74,67960,77930,91730,106090,120100,NaN,NaN
797,2,AK,Alaska,15-2031,Operations Research Analysts,detailed,120,14.1,0.364,0.49,...,35.79,44.89,70.47,43140,57980,74450,93360,146580,NaN,NaN
798,2,AK,Alaska,15-2041,Statisticians,detailed,30,8.2,0.107,0.42,...,39.62,51.67,59.66,54580,62800,82410,107470,124100,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35488,56,WY,Wyoming,15-1143,Computer Network Architects,detailed,40,30.5,0.15,0.14,...,*,*,*,*,*,*,*,*,NaN,NaN
35489,56,WY,Wyoming,15-1151,Computer User Support Specialists,detailed,590,4.3,2.19,0.51,...,22.67,27.65,32.2,30700,38490,47150,57520,66980,NaN,NaN
35490,56,WY,Wyoming,15-1152,Computer Network Support Specialists,detailed,240,4.6,0.902,0.69,...,27.88,34.06,38.86,33850,44800,57980,70850,80830,NaN,NaN
35491,56,WY,Wyoming,15-1199,"Computer Occupations, All Other",detailed,140,1.1,0.513,0.23,...,33.65,40.86,48.13,55050,63710,69990,84990,100120,NaN,NaN
36009,66,GU,Guam,15-0000,Computer and Mathematical Occupations,major,580,2.2,9.468,0.32,...,22.06,31.25,41.26,26510,34340,45890,65000,85830,NaN,NaN
36010,66,GU,Guam,15-1121,Computer Systems Analysts,detailed,70,4.2,1.107,0.27,...,22.57,26.46,30.57,29910,40860,46950,55030,63580,NaN,NaN
36011,66,GU,Guam,15-1142,Network and Computer Systems Administrators,detailed,80,10.6,1.307,0.5,...,25.07,33.34,42,35740,42120,52150,69340,87370,NaN,NaN
36012,66,GU,Guam,15-1151,Computer User Support Specialists,detailed,130,3.7,2.168,0.5,...,16.26,20.43,25.53,21630,25940,33830,42500,53100,NaN,NaN
36013,66,GU,Guam,15-1152,Computer Network Support Specialists,detailed,80,4.7,1.253,0.96,...,17.77,22.77,29.18,25890,29390,36960,47360,60700,NaN,NaN
36014,66,GU,Guam,15-1199,"Computer Occupations, All Other",detailed,100,0,1.616,0.73,...,38.76,42.75,48.13,41230,71460,80630,88910,100110,NaN,NaN
36282,72,PR,Puerto Rico,15-0000,Computer and Mathematical Occupations,major,10660,3.4,12.175,0.41,...,18.75,26.73,36.19,19910,27480,39000,55590,75280,NaN,NaN
36283,72,PR,Puerto Rico,15-1121,Computer Systems Analysts,detailed,1170,5,1.34,0.33,...,21.11,27.78,35.71,19390,29560,43900,57780,74270,NaN,NaN
36284,72,PR,Puerto Rico,15-1122,Information Security Analysts,detailed,310,23,0.35,0.47,...,20.82,24.13,32.15,26610,33220,43300,50200,66870,NaN,NaN
36285,72,PR,Puerto Rico,15-1131,Computer Programmers,detailed,1320,8.6,1.51,0.87,...,21.82,29.34,36.58,23800,32740,45380,61030,76080,NaN,NaN
36286,72,PR,Puerto Rico,15-1132,"Software Developers, Applications",detailed,260,11.8,0.301,0.05,...,26.26,34.88,43.76,29650,40180,54620,72560,91020,NaN,NaN
36287,72,PR,Puerto Rico,15-1133,"Software Developers, Systems Software",detailed,860,26.4,0.986,0.36,...,28.03,34.86,42.51,37660,46330,58310,72500,88420,NaN,NaN
36288,72,PR,Puerto Rico,15-1134,Web Developers,detailed,220,11.1,0.248,0.28,...,17.2,22.03,26.59,21880,27280,35780,45830,55300,NaN,NaN
36289,72,PR,Puerto Rico,15-1141,Database Administrators,detailed,410,6.9,0.472,0.59,...,22.59,28.75,35.62,26810,35440,46980,59800,74090,NaN,NaN
36290,72,PR,Puerto Rico,15-1142,Network and Computer Systems Administrators,detailed,940,6.8,1.074,0.41,...,20.66,28.38,36.36,26480,32560,42970,59020,75630,NaN,NaN
36291,72,PR,Puerto Rico,15-1143,Computer Network Architects,detailed,620,5.4,0.705,0.64,...,19.37,29.47,44.64,33150,35820,40290,61290,92860,NaN,NaN
36292,72,PR,Puerto Rico,15-1151,Computer User Support Specialists,detailed,3320,5.4,3.789,0.88,...,13.32,18.25,24.44,17570,20950,27710,37960,50840,NaN,NaN
36293,72,PR,Puerto Rico,15-1152,Computer Network Support Specialists,detailed,500,9.3,0.567,0.43,...,17.13,22.82,30.37,20730,26340,35630,47470,63170,NaN,NaN
36294,72,PR,Puerto Rico,15-1199,"Computer Occupations, All Other",detailed,370,20.8,0.419,0.19,...,33.22,42.75,49.03,18300,29360,69100,88920,101970,NaN,NaN
36296,72,PR,Puerto Rico,15-2031,Operations Research Analysts,detailed,80,9,0.092,0.12,...,24.51,41.23,47.61,23030,28210,50990,85770,99020,NaN,NaN
36297,72,PR,Puerto Rico,15-2041,Statisticians,detailed,230,4.8,0.267,1.04,...,17,19.32,26.61,24980,29640,35360,40190,55350,NaN,NaN
36838,78,VI,Virgin Islands,15-0000,Computer and Mathematical Occupations,major,350,5.6,9.403,0.31,...,23.87,30.34,40.55,32900,39700,49650,63120,84350,NaN,NaN
36839,78,VI,Virgin Islands,15-1121,Computer Systems Analysts,detailed,50,3.4,1.344,0.33,...,23.32,29.82,36.48,34610,40670,48510,62030,75870,NaN,NaN
36840,78,VI,Virgin Islands,15-1142,Network and Computer Systems Administrators,detailed,40,14.9,1.128,0.43,...,31.4,40.69,68.73,46860,55560,65320,84630,142960,NaN,NaN
36841,78,VI,Virgin Islands,15-1151,Computer User Support Specialists,detailed,100,18.8,2.67,0.62,...,19.23,23.87,29.21,31140,34500,39990,49650,60760,NaN,NaN
36842,78,VI,Virgin Islands,15-1152,Computer Network Support Specialists,detailed,50,17.7,1.203,0.92,...,21.33,25.12,29.26,20690,33720,44360,52250,60870,NaN,NaN

In [5]:

state_17_16_merge = pd.merge(
    com_math_17_df, state16_df, on=["OCC_CODE","STATE"], how="left",
    suffixes=("_17", "_16"))
len(state_17_16_merge)
# len(state16_df)
# com_math_17_df.groupby('OCC_CODE').count()

786

In [6]:

state_17_16_15_merge = pd.merge(
    state_17_16_merge, state15_df, on=["OCC_CODE","STATE"], how="left",
    suffixes=("", "_15"))
len(state_17_16_15_merge)

786

In [7]:
state_17_16_15_14_merge = pd.merge(
    state_17_16_15_merge, state14_df, on=["OCC_CODE","STATE"], how="left",
    suffixes=("", "_14"))
len(state_17_16_15_14_merge)

786

In [10]:
state_17_16_15_14_13_merge = pd.merge(
    state_17_16_15_14_merge, state13_df, on=["OCC_CODE","STATE"], 
    how="left",suffixes=("", "_13"))
len(state_17_16_15_14_13_merge)
allyears_df = state_17_16_15_14_13_merge
allyears_df.head()

,AREA_17,ST_17,STATE,OCC_CODE,OCC_TITLE_17,OCC_GROUP_17,TOT_EMP_17,m,JOBS_1000_17,LOC_Q_17,...,H_MEDIAN_13,H_PCT75_13,H_PCT90_13,A_PCT10_13,A_PCT25_13,A_MEDIAN_13,A_PCT75_13,A_PCT90_13,ANNUAL_13,HOURLY_13
0,1,AL,Alabama,15-0000,Computer and Mathematical Occupations,major,39760,2.3,20.68,0.69,...,34.18,44.57,55.81,37060,50890,71100,92710,116090,NaN,NaN
1,1,AL,Alabama,15-1121,Computer Systems Analysts,detailed,4010,9.4,2.084,0.51,...,37.15,45.38,55.26,49040,61700,77260,94390,114950,NaN,NaN
2,1,AL,Alabama,15-1122,Information Security Analysts,detailed,1100,7.8,0.573,0.78,...,38.81,45.32,52.71,48480,62920,80720,94260,109640,NaN,NaN
3,1,AL,Alabama,15-1131,Computer Programmers,detailed,7420,4.6,3.858,2.22,...,36.29,45.43,58.62,44800,57400,75470,94500,121930,NaN,NaN
4,1,AL,Alabama,15-1132,"Software Developers, Applications",detailed,5540,5.5,2.883,0.48,...,42.79,53.61,64.01,57070,71140,89000,111520,133140,NaN,NaN